require('./readDay.js')(1)
  .then(t => t.split(/\n\n/)
              .map(e => e.split(/\n/)
                         .reduce((a, b) => parseInt(a) + parseInt(b|0), 0))
              .sort()
              .reverse()
              .slice(0, 3)
              .reduce((a,b) => a+b, 0))
  .then(console.log)