require('./readDay.js')(3).then(i => 
  i.split('\n')
   .slice(0, -1)
   .map(l => l.split(''))
   .map(l => [l.slice(0, l.length/2), l.slice(l.length/2)])
   .map(([a,b]) => a.filter(e => b.includes(e))[0])
   .map(c => Math.max(0, c.charCodeAt(0)-96)||c.charCodeAt(0)-38)
   .reduce((x,y) => x+y, 0)
)
.then(console.log)